Added Diamond Target
GASP-UFRGS/DarkPhoton-LNLS pull request #2
Opened 2023-07-11 16:08 UTC by Febianchi

Added diamond target, made changes in .gitignore and made changes in generator.cc to randomly place the particles relatively to the diamond's plane.

2023-07-11 16:15 UTC, diemort commented
Please add a image from Geant4 in a comment here to show the simulation code is indeed working

2023-07-11 16:27 UTC, Febianchi commented
Simulation image:

![simulation_image](https://github.com/GASP-UFRGS/DarkPhoton-LNLS/assets/78316565/d114a6d1-dfbe-45fe-9c37-cca26744cc3a)

2023-07-14 01:43 UTC, diemort requested changes

2023-07-14 01:43 UTC, diemort commented on simulation/construction.cc
> +	/*
remove comments

2023-07-14 01:43 UTC, diemort commented on simulation/construction.cc
> +	/* Assembly Volumes:
remove comments

2023-07-14 01:43 UTC, diemort commented on simulation/physics.cc
> +
remove blank line

2023-07-14 01:43 UTC, diemort commented on simulation/construction.cc
> +	/*
here

2023-07-14 01:43 UTC, diemort commented on simulation/construction.cc
> +	/* Assembly Volumes:
here

2023-07-14 01:43 UTC, diemort commented on simulation/physics.cc
> +
here

2023-07-30 01:33 UTC, Febianchi commented
Commentaries were removed

2023-07-30 18:19 UTC, merged